### PR TITLE
CRB-212 install protobuf manually

### PR DESCRIPTION
**Pull request by CAGS295**

### CODE REVIEW

**Review by atodorov — APPROVED** [review]

**Comment by CAGS295** [comment]
Ignore clippy #4

**Review by atodorov — APPROVED** [review]

**Review by atodorov — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
@CAGS295 @atodorov ~~Why not just run `docker build`?~~

Edit: Nevermind, I guess I see why. It just means you'll need to make extra effort to ensure CI and the Dockerfile are kept in sync with each other, I guess.

**Comment by atodorov** [comment]
> @CAGS295 @atodorov ~Why not just run `docker build`?~
> 
> Edit: Nevermind, I guess I see why. It just means you'll need to make extra effort to ensure CI and the Dockerfile are kept in sync with each other, I guess.

That's a fair concern and I'd prefer not having to make such effort. Do you mind opening a ticket so we can take a  look at it?

**Comment by ghost** [comment]
> That's a fair concern and I'd prefer not having to make such effort. Do you mind opening a ticket so we can take a look at it?

CRB-218

**Review by seandeneen-gluwa — APPROVED** [review]

**Pull request merged**
